name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Tag Format
        run: |
          if [[ ! "${GITHUB_REF}" =~ ^refs/tags/v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            echo "Invalid tag format. Use: v<MAJOR>.<MINOR>.<PATCH> (e.g., v1.0.0)"
            exit 1
          fi

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test --configuration Release --no-restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Create NuGet Package
        run: dotnet pack --configuration Release --output ./nupkgs

      - name: Check for .nupkg
        run: |
          if ! ls nupkgs/*.nupkg 1> /dev/null 2>&1; then
            echo "No .nupkg files found. Exiting."
            exit 1
          fi

      - name: Push to NuGet Gallery
        run: |
          dotnet nuget push "nupkgs/*.nupkg" \
          --source https://api.nuget.org/v3/index.json \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --skip-duplicate || echo "Package already exists on NuGet. Skipping push."

      - name: Push to GitHub Packages
        run: |
          output=$(dotnet nuget push "nupkgs/*.nupkg" \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate)
          echo "$output"
          if echo "$output" | grep -q 'already exists'; then
            echo "Package already exists on GitHub Packages. Skipping push."
            exit 0
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .nupkg to GitHub Release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $(ls nupkgs/*.nupkg | head -n 1)
          asset_name: $(basename nupkgs/*.nupkg | head -n 1)
          asset_content_type: application/octet-stream

      - name: Notify Success
        if: success()
        run: echo "NuGet package published successfully!"

      - name: Notify Failure
        if: failure()
        run: echo "Failed to publish NuGet package."
